Add Unity container configuration
Flexberry/CodeGenSample.AspNetCorePlusEmber pull request #12
Opened 2021-07-26 12:41 UTC by mao29

As far as Flexberry ORM uses UnityFactory implicitly some services may not work correctly. This PR adds Unity Container configuration to sample generated application.

2021-07-29 05:07 UTC, NicholasNoise requested changes

2021-07-29 05:07 UTC, NicholasNoise commented on src/SuperSimpleContactList/ODataBackend/Startup.cs
> +                    const string fileControllerPath = "api/file";
Все кишки одаты по одному пути

2021-07-30 05:26 UTC, mao29 commented on src/SuperSimpleContactList/ODataBackend/Startup.cs
> +                    const string fileControllerPath = "api/file";
На роуте odata/file файловый контроллер не слушает почему-то, нам в прикладном проекте пришлось на api/file сменить

2021-07-30 05:36 UTC, mao29 commented on src/SuperSimpleContactList/ODataBackend/Startup.cs
> +                    const string fileControllerPath = "api/file";
Уточню, на фронтенде в блюпринтах путь к файловому контроллеру зашит api/file: https://github.com/Flexberry/ember-flexberry/blob/d331732b21cda6cd99aa6e005167219e33d32504/blueprints/ember-flexberry/index.js#L109

2021-08-05 07:36 UTC, kuzkok commented on src/SuperSimpleContactList/ODataBackend/Startup.cs
>              services.AddSingleton<IDataObjectFileAccessor>(
все services.AddSingleton должны уйти в ConfigureContainer и регистрироваться в юнити

2021-08-05 13:40 UTC, mao29 commented on src/SuperSimpleContactList/ODataBackend/Startup.cs
>              services.AddSingleton<IDataObjectFileAccessor>(
Вынес

2021-09-09 17:28 UTC, merged