Add CI builds for gitlab, github and Azure Dev-ops
Flexberry/CodeGenSample.AspNetCorePlusEmber pull request #16
Opened 2022-06-16 09:38 UTC by Totoro59rus

I added CI builds forgitlab, github and Azure Dev-ops

2022-06-16 11:02 UTC, mao29 requested changes

2022-06-16 11:02 UTC, mao29 commented on src/ember-app/testem.js
> -
Возможно для гитлаба можно оставить также логику с TRAVIS. У нас ведь в итоге не в нем была проблема, как выяснилось

2022-06-16 11:02 UTC, mao29 commented on azure-build/backend-build.yml
> +#   paths:
Что-то лишнее

2022-06-16 11:02 UTC, mao29 commented on .github/workflows/build.yml
> -on:
Триггеры наверное можно оставить

2022-06-16 11:02 UTC, mao29 commented on .github/workflows/build.yml
> +#       - name: Integration test under dotnet
Тоже можно оставить для гитхаба

2022-06-16 11:02 UTC, mao29 commented on azure-build/docker-build.yml
> +    dockerRegistryEndpoint: 'dh.ics.perm.ru'
А push не делается?

2022-06-16 11:02 UTC, mao29 commented on azure-build/frontend-build.yml
> +  # paths:
Что-то лишнее

2022-06-16 11:02 UTC, mao29 commented on gitlab-CI/.gitlab-ci.yml
> +  image: timbru31/node-chrome
Предлагаю тут версию образа зафиксировать

2022-06-16 11:02 UTC, mao29 commented on gitlab-CI/.gitlab-ci.yml
> +build-job:
front-job наверное по аналогии с back-job

2022-06-16 11:02 UTC, mao29 commented on src/Dockerfile
> +
А уже ведь есть Dockerfile в репозитории в одной из внутренних директорий. Зачем еще один такой же?

2023-07-28 10:00 UTC, AntonIV8 requested changes

2023-07-28 10:00 UTC, AntonIV8 commented on src/Docker/create-image.cmd
> +
Push обычно в отдельном скрипте делается. Зачем пушить каждый раз, если я например на компе экспериментирую что-то

2023-07-28 10:02 UTC, AntonIV8 requested changes

2023-07-28 10:02 UTC, AntonIV8 commented on src/Docker/create-image.cmd
> +docker push supersimplecontactlist/app
Push обычно в отдельном скрипте делается

2023-08-01 06:07 UTC, mao29 requested changes

2023-08-01 06:07 UTC, mao29 commented on src/Docker/create-image.cmd
> +docker build --no-cache -f Dockerfile.WebApi -t supersimplecontactlist/web-api ../..
Докерфайл для основного ОДатаБекенда и для образа с постгресом тоже остался, по ним тоже образы собирать нужно

2023-08-01 06:07 UTC, mao29 commented on src/Docker/push-image.cmd
> +docker push supersimplecontactlist/postgre-sql
тут надо пушить все собранные образы

2023-08-01 06:07 UTC, mao29 commented on azure-build/backend-build.yml
> +    projects: 'src/SuperSimpleContactList/Tests/bin/Debug/netcoreapp3.1/SuperSimpleContactList.Tests.dll'
тут скорее всего не netcoreapp3.1 папка должна получаться

2023-08-01 06:15 UTC, Totoro59rus commented on azure-build/backend-build.yml
> +    projects: 'src/SuperSimpleContactList/Tests/bin/Debug/netcoreapp3.1/SuperSimpleContactList.Tests.dll'
дак это тесты же

2023-08-01 06:19 UTC, mao29 commented on azure-build/backend-build.yml
> +    projects: 'src/SuperSimpleContactList/Tests/bin/Debug/netcoreapp3.1/SuperSimpleContactList.Tests.dll'
Их что-ли на 7 сдк не портировали? Если портировали, то название папки должно смениться на соответствующее 7 версии сдк

2023-08-02 10:05 UTC, mao29 requested changes

2023-08-02 10:05 UTC, mao29 commented on .github/workflows/docker-image.yml
> +      run: cd src/Docker | sh create-image.cmd
Оно не соберется на линуксе, там пути виндовые

2023-08-02 11:00 UTC, mao29 approved these changes

2023-08-08 04:24 UTC, AntonIV8 approved these changes

2023-08-08 04:25 UTC, merged