Add WebApi project with Unity, healthcheck, CurrentUser and sample co…
Flexberry/CodeGenSample.AspNetCorePlusEmber pull request #17
Opened 2023-07-25 06:36 UTC by AntonIV8

…ntroller

2023-07-25 06:45 UTC, TeterinaSvetlana commented on src/SuperSimpleContactList/ODataBackend/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
ой а что это

2023-07-25 06:45 UTC, TeterinaSvetlana commented on src/SuperSimpleContactList/WebApi/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
и тут

2023-07-25 06:45 UTC, TeterinaSvetlana commented on src/SuperSimpleContactList/WebApi/Program.cs
> +    /// �������� ����� ����������.
опять что-то с кодировкой и ниже тоже есть

2023-07-25 06:49 UTC, mao29 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
Что-то с кодировкой

2023-07-25 06:49 UTC, mao29 commented on src/SuperSimpleContactList/WebApi/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
аналогично

2023-07-25 06:49 UTC, mao29 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
А эта секция все-таки нужна?

2023-07-25 06:49 UTC, mao29 commented on src/SuperSimpleContactList/WebApi/App.config
> +  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
аналогично

2023-07-25 06:49 UTC, mao29 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +                return new JsonResult(errorMessage);
Возвращать в ответе стек-трейс мне кажется не очень безопасная и правильная практика. В сэмпле бы что-то более образцовое сделать

2023-07-25 06:49 UTC, mao29 commented on src/SuperSimpleContactList/WebApi/Program.cs
> +            container.RegisterSingleton<IDataService, PostgresDataService>(
А в старом конфиге вроде лайфтайм синглтон был по факту HierarchicalLifetimeManager-ом, то есть по инстансу на запрос вроде создавалось... Действительно датасервис прям совсем может синглтоном быть?

2023-07-25 06:57 UTC, bratchikov requested changes

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/ODataBackend/App.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
BOM лучше убрать, вроде и без него с UTF-8 всё хорошо в современных редакторах.

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/ODataBackend/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
Пересохрани-ка этот файл в UTF-8.

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/ODataBackend/App.config
> +    <appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
А зачем нужен ConsoleAppender из коробки?

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +            this.user = user;
А контроллер создаётся на каждый http-запрос отдельно?

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +        public IActionResult Get()
Лучше в качестве примера сделать какую-нибудь функцию, которой нет в OData.

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +                var lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(Contact), Contact.Views.ContactE);
Тут используется очень плохая практика - читать объект по E-представлению (обычно там много всяких мастеров и пр.). Потом, ниже по коду, ничего из вычитанного тут не используется кроме имени. Чтобы сделать правильно - тут вообще не нужен даже LoadObjects, а сделать LoadObjectsStringedView с представлением с одним полем.

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +                string errorMessage = "Request error - " + ex;
"-" в этом случае вроде бы не пишут. С т.з. конечного пользователя он вряд ли делал Request. Там наверное какая-то операция прикладного уровня была, которая как-то отражена в названии метода контроллера.

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Program.cs
> +namespace NewPlatform.SuperSimpleContactList
Пересохрани все файлы в UTF-8.

2023-07-25 06:57 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/SuperSimpleContactList.WebApi.csproj
> +    <PackageReference Include="NewPlatform.Flexberry.ORM.PostgresDataService" Version="6.0.0" />
Бери последние стабильные версии.

2023-07-25 06:58 UTC, bratchikov commented
я бы ещё добавил editorconfig

2023-07-25 06:58 UTC, bratchikov commented
Анализатор стиля кода надо по умолчанию включить для всех проектов. Ну и проверить, что студия не ругается ни на что.

2023-07-25 08:28 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +            this.user = user;
да

2023-07-25 09:12 UTC, mao29 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +        public IActionResult Get()
Тут ведь не ОДата

2023-07-25 12:09 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/App.config
> +  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
Убрал

2023-07-25 12:09 UTC, AntonIV8 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
Убрал

2023-07-25 12:09 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
Убрал

2023-07-25 12:10 UTC, AntonIV8 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
Поправил

2023-07-25 12:10 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Program.cs
> +    /// �������� ����� ����������.
Поправил

2023-07-25 12:11 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +                return new JsonResult(errorMessage);
Вернул string, подойдет ?

2023-07-25 12:11 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Program.cs
> +            container.RegisterSingleton<IDataService, PostgresDataService>(
Поменял. Я так тоже сам не делал, это вроде генератор выдает так. Надо над этим моментом подумать почитать

2023-07-25 12:11 UTC, AntonIV8 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +﻿<?xml version="1.0" encoding="utf-8"?>
Убрал

2023-07-25 12:12 UTC, AntonIV8 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +    <!--Остатки ОРМ которые должны быть в конфиге-->
Сохранил

2023-07-25 12:12 UTC, AntonIV8 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +    <appender name="ConsoleAppender" type="log4net.Appender.ConsoleAppender">
Может надо все-таки ? По мне так полезно, вроде и в докере в терминал выводит он, чем часто пользуюсь

2023-07-25 12:13 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +            this.user = user;
Я там тип поменял при регистрации этих сервисов

2023-07-25 12:13 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +        public IActionResult Get()
Я тут не очень понял, но на всяк случай переименовал Get

2023-07-25 12:14 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +                var lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(Contact), Contact.Views.ContactE);
Сделал через  LoadObjectsStringedView

2023-07-25 12:14 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +                string errorMessage = "Request error - " + ex;
Поправил

2023-07-25 12:14 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Program.cs
> +namespace NewPlatform.SuperSimpleContactList
Сохранил

2023-07-25 12:14 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/SuperSimpleContactList.WebApi.csproj
> +    <PackageReference Include="NewPlatform.Flexberry.ORM.PostgresDataService" Version="6.0.0" />
Обновил

2023-07-25 13:02 UTC, bratchikov approved these changes

2023-07-26 09:42 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Controllers/Home.cs
> +                View view = new View();
Непонятно что делать в генераторе с этим методом. Не будем ведь генерировать такое каждый раз.

2023-07-26 09:42 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Program.cs
> +            builder.Services.AddCors(o => o.AddPolicy("MyPolicy", builder =>
Вот тут обязательно надо добавить комментарий, что CORS для любых запросов надо выключить на проде. Мы не хотим это вынести в конфиг? Как правильно собирать прод без разрешений, а тестовый стенд с разрешениями?

2023-07-26 09:42 UTC, bratchikov commented on src/SuperSimpleContactList/WebApi/Properties/launchSettings.json
> +        "DefConnStr": "SERVER=localhost;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;"
А можно как-то сонару сказать, чтобы он этот файл не проверял, а то ругается на пароль?

2023-07-26 09:51 UTC, mao29 commented on src/SuperSimpleContactList/WebApi/Properties/launchSettings.json
> +        "DefConnStr": "SERVER=localhost;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;"
А я бы предложил не писать пароли в конфиге. Есть механизм секретов вроде для дотнета, через который можно секретные параметры в конфиг подкладывать

2023-07-26 09:59 UTC, mao29 commented on src/SuperSimpleContactList/WebApi/Program.cs
> +            builder.Services.AddCors(o => o.AddPolicy("MyPolicy", builder =>
Можно сделать через IsDevelopment(), как для страницы показа стектрейса ошибок делается

2023-07-26 11:46 UTC, AntonIV8 commented on src/SuperSimpleContactList/WebApi/Program.cs
> +            builder.Services.AddCors(o => o.AddPolicy("MyPolicy", builder =>
Я добавил WithOrigins, который указан в AllowedHosts в appsettings

2023-07-27 04:04 UTC, merged