Upgrade to net7
Flexberry/CodeGenSample.AspNetCorePlusEmber pull request #18
Opened 2023-07-25 08:37 UTC by TeterinaSvetlana

2023-07-25 11:38 UTC, Anisimova2020 commented on src/SuperSimpleContactList/BusinessServers/SuperSimpleContactList.BusinessServers.csproj
> +    <PackageReference Include="NewPlatform.Flexberry.ORM" Version="7.0.0" />
Лучше сразу 7.1.1 взять

2023-07-25 11:39 UTC, Anisimova2020 commented on src/SuperSimpleContactList/IntegrationTests/SuperSimpleContactList.IntegrationTests.csproj
> +    <PackageReference Include="NewPlatform.Flexberry.ORM.PostgresDataService" Version="7.0.0" />
При смене версии ОРМ до 7.1.1 важно не забыть PostgresDataService тоже до 7.1.1 поднять.

2023-07-25 11:42 UTC, Anisimova2020 commented on src/SuperSimpleContactList/ODataBackend/SuperSimpleContactList.ODataBackend.csproj
> +    <PackageReference Include="NewPlatform.Flexberry.ORM.ODataService" Version="7.0.0" />
И одату лучше сразу до 7.1.1.

2023-07-26 05:00 UTC, AntonIV8 requested changes

2023-07-26 05:00 UTC, AntonIV8 commented on src/SuperSimpleContactList/BusinessServers/SuperSimpleContactList.BusinessServers.csproj
> +    <PackageReference Include="NewPlatform.Flexberry.ORM" Version="7.0.0" />
Ага

2023-07-26 05:00 UTC, AntonIV8 commented on src/SuperSimpleContactList/ODataBackend/App.config
> +  <unity xmlns="http://schemas.microsoft.com/practices/2010/unity">
Регистрации вроде в коде все. Раздел Unity вообще не надо

2023-07-26 05:00 UTC, AntonIV8 commented on src/SuperSimpleContactList/ODataBackend/Properties/launchSettings.json
> +        "ASPNETCORE_ENVIRONMENT": "Development"
А тут точно надо было убрать ? Для чего это в launch.settings было ?

2023-07-26 07:47 UTC, TeterinaSvetlana commented on src/SuperSimpleContactList/ODataBackend/Properties/launchSettings.json
> +        "ASPNETCORE_ENVIRONMENT": "Development"
это для запуска в разных средах, в проекте только одна, решила убрать потому что BackendRoot и DefConnStr прописала в appsettings. ну в общем вернула сюда обратно тоже

2023-07-26 08:24 UTC, AntonIV8 approved these changes

2023-07-26 08:24 UTC, merged